version: '3'
services:
    app:
        build: .
        tty: true
        deploy:
            resources:
                reservations:
                    devices:
                        - capabilities: [gpu]
        volumes:
          - .:/stable-diffusion